version: '3'

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest #mongo:latest
    working_dir: /app
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker/.data/mongo:/data/mongo

  nodejs:
    container_name: nodejs
    working_dir: /app
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - node_modules:/app/node_modules
      - ./:/app

volumes:
  my_data:
  node_modules: