version: '3.8'
#node-web >>> docker
#node-web >>> nodejs
#"5000:5000" >>> "3000:3000"
services:

    mongodb:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - docker/.data/.mongodb:/data/db/mongodb

    nodejs:
        build:
            context: ./docker
            dockerfile: Dockerfile
        depends_on:
            - mongodb
        volumes:
            - /app/node_modules
            - ./:/app
        ports:
            - "3000:3000"

volumes:
    docker/.data/.mongodb: