version: '3'

services:
  nodejs:
    build:
      context: ../
      dockerfile: Dockerfile
    image: nodejs
    working_dir: /App
    container_name: nodejs
    restart: unless-stopped
    env_file: ../.env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWD=$MONGO_PASSWD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 80:8080
    volumes:
      - ../:/App
      - ../node_modules:/App/node_modules
    networks:
      - app-network
    command: ../wait-for.sh mongo:27017 -- /App/node_modules/.bin/nodemon app.js

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: ../.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./.data/mongo:/data/mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
